services:
  # AWS (LocalStack) container
  # https://hub.docker.com/r/localstack/localstack
  aws:
    container_name: container-aws
    image: localstack/localstack:4.0.3
    environment:
      DEBUG: "0"
      EAGER_SERVICE_LOADING: "0"
      SERVICES: kms,s3
      AWS_ENDPOINT_URL: http://localhost:4566
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
    networks:
      - default
    ports:
      - 4566:4566
    volumes:
      - .docker/aws/init:/etc/localstack/init/ready.d:ro

  # Database (MySQL) container
  # https://hub.docker.com/_/mysql
  db:
    container_name: container-db
    image: mysql:8.0.40-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    networks:
      - default
    ports:
      - 3306:3306
    tmpfs:
      - /var/lib/mysql
    volumes:
      - .docker/db/conf:/etc/mysql/conf.d:ro
      - .docker/db/init:/docker-entrypoint-initdb.d:ro

  # KVS (Valkey) container
  # https://hub.docker.com/r/valkey/valkey
  kvs:
    container_name: container-kvs
    image: valkey/valkey:8.0.1-bookworm
    networks:
      - default
    ports:
      - 6379:6379

  # Deno container
  # https://hub.docker.com/r/denoland/deno
  deno:
    container_name: container-deno
    image: denoland/deno:debian-2.1.4
    environment:
      AWS_ENDPOINT_URL: http://aws:4566
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_REGION: ap-northeast-1
      AWS_ACCESS_KEY_ID: dummy
      AWS_SECRET_ACCESS_KEY: dummy
      DB_URL: mysql://username:password@db:3306/dbname
      KVS_URL: redis://kvs:6379
    networks:
      - default
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["/bin/bash"]
    tty: true

networks:
  default:
    name: network-default
